### PR TITLE
chore(prisma-crud-generator): fix typo

### PR DESCRIPTION
**Pull request by jsw**

### CODE REVIEW

**Comment by johannesschobel** [comment]
Dear @jsw ,

thanks for contributing. can you please use proper commit messages? i.e., 
```
chore(prisma-crud-generator): fix typo
```

and force push again?
All the best

**Comment by devth** [comment]
LGTM. :shipit:  💯

**Comment by johannesschobel** [comment]
i meant the commit message not the PR title - sorry for the possible confusion.
It may not be possible to change commit messages directly via the github website.

if you use a sophisticated IDE (i.e., vscode) there are some husky hooks that check for commit messages :) but that does not work when directly contributing via the website - unfortunately.

nevertheless, i have fixed the typo in my code and pushed respectively.

thanks for noticing the typo and contributing! :)

**Comment by jsw** [comment]
Gotcha. A colleague had mentioned using this GitHub Action to enforce PR titles, not individual commits, so I thought that might work here as well. :-) 

https://github.com/amannn/action-semantic-pull-request

**Pull request closed without merging**
